# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cilk Hub
email: cilk@mit.edu
description: 'Cilk Hub seeks to provide quality open-source parallel-programming software and support services for the benefit of application programmers and computer-science researchers.'
baseurl: '' # the subpath of your site, e.g. /blog
url: http://cilk.mit.edu # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
# theme: minima
# theme: minimal-mistakes-jekyll
highlighter: pygments
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at
  - 'jekyll/scholar'
asciidoc:
  ext: asciidoc,adoc,ad
asciidoctor-enabled: true
asciidoctor:
  attributes:
    imagesdir: /assets/img
    source-highlighter: pygments
    pygments-css: emacs
    sectanchors: ''
    linkattrs: ''
    stem: latexmath
    mathjax: ''
    icons: font
    safe: ''
    xrefstyle: short
    cilkpp: Cilk++
    clangpp: clang++
    tapir-release: 1.0-3
    llvm-base: 5
    issueTracker: link:https://github.com/wsmoses/Parallel-IR/issues[issue tracker, window="_blank"]
    underConstruction: image:http://textfiles.com/underconstruction/TokyoPagoda6968UnderConstruct.gif[]
    page-liquid: ''

#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed

#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/footer_scripts

google_analytics_tracking_id: UA-111688461-1

scholar:
    source: _papers
    bibliography: allpapers.bib
    sort_by: author

# The language setting is used in /includes/header.html for html-settings
language: 'en'

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: true 	# Hide metadata for all pages
      sidebar: right   		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: CilkHub     # Default author for pages
      header: title
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      # author: phlow     # Default author for posts
      header: title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
