- menu_name: "Services"

- name: "Accessibility"
  url: "http://accessibility.mit.edu"
  title: "Accessibility"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
